# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: cpamain
services:
  mysql:
    extends:
      file: ./mysql.yml
      service: mysql
  memcached:
    extends:
      file: ./memcached.yml
      service: memcached
