package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AgencyLicenseTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgencyLicenseTypeAllPropertiesEquals(AgencyLicenseType expected, AgencyLicenseType actual) {
        assertAgencyLicenseTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertAgencyLicenseTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgencyLicenseTypeAllUpdatablePropertiesEquals(AgencyLicenseType expected, AgencyLicenseType actual) {
        assertAgencyLicenseTypeUpdatableFieldsEquals(expected, actual);
        assertAgencyLicenseTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgencyLicenseTypeAutoGeneratedPropertiesEquals(AgencyLicenseType expected, AgencyLicenseType actual) {
        assertThat(expected)
            .as("Verify AgencyLicenseType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgencyLicenseTypeUpdatableFieldsEquals(AgencyLicenseType expected, AgencyLicenseType actual) {
        assertThat(expected)
            .as("Verify AgencyLicenseType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getIsActive()).as("check isActive").isEqualTo(actual.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgencyLicenseTypeUpdatableRelationshipsEquals(AgencyLicenseType expected, AgencyLicenseType actual) {}
}
