package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CityCorpPouraAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityCorpPouraAllPropertiesEquals(CityCorpPoura expected, CityCorpPoura actual) {
        assertCityCorpPouraAutoGeneratedPropertiesEquals(expected, actual);
        assertCityCorpPouraAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityCorpPouraAllUpdatablePropertiesEquals(CityCorpPoura expected, CityCorpPoura actual) {
        assertCityCorpPouraUpdatableFieldsEquals(expected, actual);
        assertCityCorpPouraUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityCorpPouraAutoGeneratedPropertiesEquals(CityCorpPoura expected, CityCorpPoura actual) {
        assertThat(expected)
            .as("Verify CityCorpPoura auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityCorpPouraUpdatableFieldsEquals(CityCorpPoura expected, CityCorpPoura actual) {
        assertThat(expected)
            .as("Verify CityCorpPoura relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCityCorpPouraUpdatableRelationshipsEquals(CityCorpPoura expected, CityCorpPoura actual) {
        assertThat(expected)
            .as("Verify CityCorpPoura relationships")
            .satisfies(e -> assertThat(e.getDistrict()).as("check district").isEqualTo(actual.getDistrict()))
            .satisfies(e -> assertThat(e.getUpazila()).as("check upazila").isEqualTo(actual.getUpazila()))
            .satisfies(e -> assertThat(e.getRmo()).as("check rmo").isEqualTo(actual.getRmo()));
    }
}
