package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DesignationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignationAllPropertiesEquals(Designation expected, Designation actual) {
        assertDesignationAutoGeneratedPropertiesEquals(expected, actual);
        assertDesignationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignationAllUpdatablePropertiesEquals(Designation expected, Designation actual) {
        assertDesignationUpdatableFieldsEquals(expected, actual);
        assertDesignationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignationAutoGeneratedPropertiesEquals(Designation expected, Designation actual) {
        assertThat(expected)
            .as("Verify Designation auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignationUpdatableFieldsEquals(Designation expected, Designation actual) {
        assertThat(expected)
            .as("Verify Designation relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getShortName()).as("check shortName").isEqualTo(actual.getShortName()))
            .satisfies(e -> assertThat(e.getIsActive()).as("check isActive").isEqualTo(actual.getIsActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDesignationUpdatableRelationshipsEquals(Designation expected, Designation actual) {}
}
