package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DistrictAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDistrictAllPropertiesEquals(District expected, District actual) {
        assertDistrictAutoGeneratedPropertiesEquals(expected, actual);
        assertDistrictAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDistrictAllUpdatablePropertiesEquals(District expected, District actual) {
        assertDistrictUpdatableFieldsEquals(expected, actual);
        assertDistrictUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDistrictAutoGeneratedPropertiesEquals(District expected, District actual) {
        assertThat(expected)
            .as("Verify District auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDistrictUpdatableFieldsEquals(District expected, District actual) {
        assertThat(expected)
            .as("Verify District relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDistrictUpdatableRelationshipsEquals(District expected, District actual) {
        assertThat(expected)
            .as("Verify District relationships")
            .satisfies(e -> assertThat(e.getDivision()).as("check division").isEqualTo(actual.getDivision()));
    }
}
