package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DivisionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDivisionAllPropertiesEquals(Division expected, Division actual) {
        assertDivisionAutoGeneratedPropertiesEquals(expected, actual);
        assertDivisionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDivisionAllUpdatablePropertiesEquals(Division expected, Division actual) {
        assertDivisionUpdatableFieldsEquals(expected, actual);
        assertDivisionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDivisionAutoGeneratedPropertiesEquals(Division expected, Division actual) {
        assertThat(expected)
            .as("Verify Division auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDivisionUpdatableFieldsEquals(Division expected, Division actual) {
        assertThat(expected)
            .as("Verify Division relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDivisionUpdatableRelationshipsEquals(Division expected, Division actual) {}
}
