package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RMOAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRMOAllPropertiesEquals(RMO expected, RMO actual) {
        assertRMOAutoGeneratedPropertiesEquals(expected, actual);
        assertRMOAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRMOAllUpdatablePropertiesEquals(RMO expected, RMO actual) {
        assertRMOUpdatableFieldsEquals(expected, actual);
        assertRMOUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRMOAutoGeneratedPropertiesEquals(RMO expected, RMO actual) {
        assertThat(expected)
            .as("Verify RMO auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRMOUpdatableFieldsEquals(RMO expected, RMO actual) {
        assertThat(expected)
            .as("Verify RMO relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRMOUpdatableRelationshipsEquals(RMO expected, RMO actual) {}
}
