package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UpazilaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUpazilaAllPropertiesEquals(Upazila expected, Upazila actual) {
        assertUpazilaAutoGeneratedPropertiesEquals(expected, actual);
        assertUpazilaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUpazilaAllUpdatablePropertiesEquals(Upazila expected, Upazila actual) {
        assertUpazilaUpdatableFieldsEquals(expected, actual);
        assertUpazilaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUpazilaAutoGeneratedPropertiesEquals(Upazila expected, Upazila actual) {
        assertThat(expected)
            .as("Verify Upazila auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUpazilaUpdatableFieldsEquals(Upazila expected, Upazila actual) {
        assertThat(expected)
            .as("Verify Upazila relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUpazilaUpdatableRelationshipsEquals(Upazila expected, Upazila actual) {
        assertThat(expected)
            .as("Verify Upazila relationships")
            .satisfies(e -> assertThat(e.getDistrict()).as("check district").isEqualTo(actual.getDistrict()));
    }
}
